### PR TITLE
[WIP] experiment to use pyproject.toml instead of setup.py

### PR DESCRIPTION
**Pull request by karlicoss**

### CODE REVIEW

**Comment by karlicoss** [comment]
@seanbreckenridge not sure if you used pyproject.toml before, but this is surprisingly nice, quite a bit less boilerplate. I might experiment with switching some small projects first
btw how are you uploading to pypi in your projects, haven't found it in CI -- are you doing it from cmdline?

**Comment by seanbreckenridge** [comment]
I've used it a few times Ive been forced to, and might be nice to switch, but [my template sets lots of other stuff](https://github.com/seanbreckenridge/cookiecutter-template/blob/master/%7B%7Bcookiecutter.module_name%7D%7D/setup.cfg) I dont think you do.

I think the major thing I'm holding out for is [flake8](https://github.com/PyCQA/flake8/issues/234#issuecomment-812800722), (related: <https://github.com/psf/black/issues/683>)

dont really want to have the config split between even more files, and am pretty happy with the declarative stuff in setup.cfg and just having an empty setup.py with a call to `setup`

> btw how are you uploading to pypi in your projects, haven't found it in CI -- are you doing it from cmdline

Yeah, I just do a:

```
rm -rf build dist; python3 -m build && twine upload -r pypi dist/*
```

**Comment by seanbreckenridge** [comment]
I think I planned to switch 2 years ago or so, but editable installs had not been implemented yet

I think with https://peps.python.org/pep-0660/ they have been now

**Comment by karlicoss** [comment]
Yep, I tested editables as well, seems to work fine!

**Comment by seanbreckenridge** [comment]
Related to <https://github.com/seanbreckenridge/reorder_editable/issues/2>, seems that if a pyproject file is even present (like even just `touch pyproject.toml`), pip will do a isolated (pep517) build

gonna play around with that in relation to reorder_editable, to see if its possible to still override namespace packages like we've been doing

**Comment by karlicoss** [comment]
Btw, I'm thinking that even with the 'old' setup scheme, if packages are installed normally, not like editable, there is no way to specify the order right? Perhaps if it's inevitable to use some extra config, or some `__path__` hacking in the long run :(

**Comment by seanbreckenridge** [comment]
Huh, I've actually never tried to do that, but when I do, it overwrites the files in the single `my` folder (makes sense, thats what namespace packages are meant to do).

I could see that getting real confusing to debug, as my/your modules are intermixed


```
[ /tmp/fkiBXyVzZ0/venv/lib/python3.11/site-packages/my ] $ ls
\ls activitywatch reddit  
activitywatch:
active_window.py  __pycache__

reddit:
all.py	common.py  __init__.py	pushshift.py  __pycache__  rexport.py
```

But like, that might work...?

like, the `ip` folder looks like this:

```
$ \ls        
all.py	blizzard.py  common.py	discord.py  facebook.py  __main__.py  __pycache__
```

I installed in order: Your HPI (which has `common.py` for example), My HPI (which has an `all.py` and `facebook.py`), then my HPI-personal (which it correctly grabbed my `all.py` file from and overwrote it in the directory)

```
[ /tmp/fkiBXyVzZ0/venv/lib/python3.11/site-packages/my/ip ] $ ccat all.py
"""
Combines IPs from data exports which include IP addresses
"""

REQUIRES = ["git+https://github.com/seanbreckenridge/ipgeocache"]

from typing import Iterator

from my.ip.common import IP  # type: ignore[import]
from my.core.common import LazyLogger, Stats
from my.core.denylist import DenyList

logger = LazyLogger(__name__)


# helper to get path to data file in my data directory
from my.utils.backup_to.__main__ import get_dir as hpi_data_file

denydir = hpi_data_file("denylist")
deny = DenyList(denydir / "ips.json")


def _ips() -> Iterator[IP]:
    # can add more sources here, or disable them through core.disabled_modules
    from my.ip import facebook, discord, blizzard

    yield from facebook.ips()
    yield from discord.ips()
    yield from blizzard.ips()


def ips() -> Iterator[IP]:
    yield from deny.filter(_ips())


def stats() -> Stats:
    from my.core import stat

    return {**stat(ips)}
```

Running `pip install HPI` and `pip install HPI-personal` (my two repos), I can see the `all.py` file get overwritten, looks like that would work...

If there was just a script that figured out what your environment was and did something like:

```
pip install --no-deps karlicoss/HPI
pip install --no-deps seanbreckenridge/HPI
pip install --no-deps seanbreckenridge/HPI-personal
```

(or maybe this is just a bit of configuration in `my.core`, then that doesnt seem too bad.

Might not have hit the rough edge yet, but other than it not being editable (meaning you have to pip install it and changes arent immediately reflected), doesnt seem too bad

**Comment by seanbreckenridge** [comment]
Will say, thats not as nice as the current ergonomics, having everything be in its separate directory but still combined into the single `my` package, but with a small command to re-install things, doesnt seem that bad either. The reordering the `.pth` file was always a hack to begin with.

Also, me and you are definitely not the common case, if someone is even going to use more than one HPI repository, they'd setup the order of the repos they wanted once. Then, any time they pull/make a change, they would do `hpi pip-install` or something, and that'd be it.

**Pull request merged**
